# Generated by Django 3.2.6 on 2023-09-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=32)),
                ('region', models.CharField(max_length=32)),
                ('district', models.CharField(max_length=32)),
                ('vaccination_center', models.CharField(max_length=100)),
            ],
        ),
    ]
