# Generated by Django 4.2.5 on 2023-09-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="vaccination_center",
        ),
    ]
