# Generated by Django 3.2.6 on 2023-09-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immunization_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_administaration', models.DateTimeField()),
                ('next_date_of_administration', models.DateTimeField()),
            ],
        ),
    ]
