# Generated by Django 3.2.6 on 2023-09-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Immunization_Record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization_record',
            name='date_of_administaration',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='immunization_record',
            name='next_date_of_administration',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
