# Generated by Django 3.2.6 on 2023-09-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_vaccination_center'),
        ('registration', '0002_auto_20230914_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthworker',
            name='location',
        ),
        migrations.AddField(
            model_name='healthworker',
            name='location',
            field=models.ManyToManyField(to='location.Location'),
        ),
    ]
