# Generated by Django 4.2.3 on 2023-09-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='gender',
        ),
    ]
