# Generated by Django 4.2.5 on 2023-09-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_remove_guardian_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
