# Generated by Django 3.2.6 on 2023-09-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_vaccination_center'),
        ('child', '0003_alter_child_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='location',
        ),
        migrations.AddField(
            model_name='guardian',
            name='location',
            field=models.ManyToManyField(to='location.Location'),
        ),
    ]
